---
title: "Unsafe Countries for Americans"
author: "Thomas Gredig"
date: "4/10/2019"
output:
  html_document:
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(stringr)
library(knitr)
```


# Making Maps

An example on how to make a colored world map.


## Unsafe Countries to Travel

According to the US State Department and reported on [CNN](https://www.cnn.com/2019/04/10/politics/state-department-travel-advisory-kidnapping-risk/index.html), the following countries have **K** indicator, meaning that Americans are warned of kidnapping.d

```{r}
library(rworldmap)
list.str = "Afghanistan, Algeria, Angola, Bangladesh, Burkina Faso, Cameroon, Central African Republic, Colombia, Democratic Republic of the Congo, Ethiopia, Haiti, Iran, Iraq, Kenya, Lebanon, Libya, Malaysia, Mali, Mexico, Niger, Nigeria, Pakistan, Papua New Guinea, Philippines, Russian Federation, Somalia, South Sudan, Sudan, Syria, Trinidad and Tobago, Turkey, Uganda, Ukraine (in Russian-controlled eastern Ukraine), Venezuela, and Yemen"
# clean up data
gsub(",and","",list.str) -> list.str
gsub("\\(.*\\)?","", list.str) -> list.str
list.ctr = data.frame( country = str_trim(strsplit(list.str,',')[[1]])
)
list.ctr$value = 1: nrow(list.ctr)
```

The listed countries are:

```{r}
kable(list.ctr)
```

## Map

Here is the map:

```{r}
mapDevice('x11')
spdf <- joinCountryData2Map(list.ctr, joinCode="NAME", nameJoinColumn="country")
mapCountryData(spdf, nameColumnToPlot="value", catMethod="fixedWidth")
```

